language: php
php:
  - 5.5
  - 5.4
  - hhvm
before_install:
  - sudo apt-get update
  - sudo apt-get install php-pear
before_script:
  - sudo pear channel-discover pear.bovigo.org
  - sudo pear install bovigo/vfsStream-beta